Switch to ESM, change node requirement to node 14
SamVerschueren/decode-uri-component pull request #11
Opened 2022-12-14 07:38 UTC by void-spark

2022-12-14 15:51 UTC, SamVerschueren requested changes
Gave some feedback. I think overall this is pretty good 👍 .

Can you also update the `readme.md` to use `import decodeURIComponent from 'decode-uri-component';` instead of the require?

2022-12-14 15:51 UTC, SamVerschueren commented on index.mjs
> +	} catch (error) {
Remove the `(error)` binding here. I believe it's not needed anymore.

2022-12-14 15:51 UTC, SamVerschueren commented on index.mjs
> +	} catch (error) {
If we do that everywhere, we can remove the disabled `unicorn/prefer-optional-catch-binding`.

2022-12-14 15:51 UTC, SamVerschueren commented on .github/workflows/main.yaml
> +          - '19'
Remove `19`. I only care about LTS (just like `query-string`)

2022-12-14 15:51 UTC, SamVerschueren commented on test.mjs
> +	'\uFEFFtest2': '\uFEFFtest2',
Any reason this was updated?

2022-12-14 15:51 UTC, SamVerschueren commented on test.mjs
> +import m from './index.mjs';
Rename the test file back to `test.js`.

2022-12-15 11:44 UTC, void-spark commented on test.mjs
> +	'\uFEFFtest2': '\uFEFFtest2',
It caused the same test title twice ('test -> test'), which isn't allowed with the new test libraries.

2022-12-15 11:48 UTC, void-spark commented on package.json
> +		"index.mjs"
Done

2022-12-15 11:49 UTC, void-spark commented on test.mjs
> +import m from './index.mjs';
Done

2022-12-15 11:50 UTC, void-spark commented on .github/workflows/main.yaml
> +          - '19'
Done

2022-12-15 11:52 UTC, void-spark commented on package.json
> +	"version": "0.3.0",
Done

2022-12-15 11:52 UTC, void-spark commented on package.json
> +		"default": "./index.mjs"
Done

2022-12-15 12:01 UTC, void-spark commented on index.mjs
> +	} catch (error) {
done

2022-12-15 12:01 UTC, void-spark commented on index.mjs
> +		} catch (error) {
done

2022-12-15 12:01 UTC, void-spark commented on index.mjs
> +	} catch (error) {
done

2022-12-15 12:02 UTC, void-spark commented on index.mjs
> +	} catch (error) {
done and done

2022-12-15 12:03 UTC, void-spark commented on index.mjs
> +/* eslint-disable unicorn/prefer-optional-catch-binding,no-unused-vars,import/no-anonymous-default-export */
The (error), which is now gone :)

2022-12-15 12:17 UTC, void-spark commented on index.mjs
> +export default function (encodedURI) {
Yep, and done.
Only I used 'decodeUriComponent' instead of the existing/system 'decodeURIComponent', which explodes the test.

2022-12-15 14:05 UTC, SamVerschueren approved these changes

2022-12-15 14:22 UTC, merged

2022-12-15 14:22 UTC, SamVerschueren commented
Awesome work @void-spark 🙏 !

2022-12-15 14:32 UTC, SamVerschueren commented
Released as 0.4.0.

2022-12-16 08:22 UTC, void-spark commented
Well, now @sindresorhus just needs to update the dependencies to the ECM versions:
    "decode-uri-component": "^0.4.0",
    "split-on-first": "^3.0.0"
Seems anyone who hasn't committed to query-string cannot open or comment on issues anymore, so hope he sees this :)

2022-12-16 10:05 UTC, SamVerschueren commented
Just sent a PR to the `query-string` package with the updated versions.

2023-02-18 22:54 UTC, zezo2019 approved these changes

2023-03-07 23:29 UTC, HAWKS3CURE commented
void-spark:main.patch:x

2023-04-02 05:08 UTC, sandritis2 commented
14